name: publish-lambda-action

author: Heronlabs

description: Publish Lambda image

inputs:
  AWS_ACCESS_KEY_ID:
    description: inputs.AWS_ACCESS_KEY_ID
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: inputs.AWS_SECRET_ACCESS_KEY
    required: true
  AWS_REGION:
    description: inputs.AWS_REGION
    required: true
  LAMBDA_IMAGE:
    description: inputs.LAMBDA_IMAGE
    required: true
  LAMBDA_NAME:
    description: inputs.LAMBDA_NAME
    required: true

runs:
  using: composite
  steps:
    - name: '[PUBLISH] | Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}

    - name: '[PUBLISH] | Publish image on AWS Lambda function'
      shell: bash
      run: |
         chmod +x ./publish-lambda-action/core/publish-lambda-bucket.sh
         ./publish-lambda-action/core/publish-lambda-bucket.sh
      env:
        LAMBDA_IMAGE: ${{ inputs.LAMBDA_IMAGE }}
        LAMBDA_NAME:  ${{ inputs.LAMBDA_NAME }}
